import { DealsConstants } from '../../utils/constants'

const {
  platformOptions,
  sourceOptions,
  industryOptions,
  companySizeOptions,
  currencyOptions,
  brandCategories,
  paymentTermsOptions,
  CreateDealSections,
  toneOptions,
  contentOptions,
} = DealsConstants

const CreateDealForm = {}

CreateDealForm[CreateDealSections.BasicInfo.key] = {
  uid: `${CreateDealSections.BasicInfo.key}_section_1`,
  title: CreateDealSections.BasicInfo.label,
  fields: [
    {
      uid: `${CreateDealSections.BasicInfo.key}.deal_title`,
      label: 'Deal Title',
      name: 'title', // Deal Title
      component: 'textInput',
      type: 'text',
      style: '', // Custom Css Classes
      required: true,
      default: '', // Default Value
      placeholder: 'Instagram Campaign - Nike',
      colSpan: 12, // Grid Item Property
      options: [], // In case of type == dropdown
      validations: [],
      config: {},
      group: {}, // if component === 'group'
    },
    {
      uid: `${CreateDealSections.BasicInfo.key}.brand_name`,
      label: 'Brand Name',
      name: 'brandName',
      component: 'textInput',
      type: 'text',
      style: '',
      required: true,
      default: '',
      placeholder: 'Nike India',
      colSpan: null,
      options: [],
      validations: [],
      config: {},
      group: {},
    },
    {
      uid: `${CreateDealSections.BasicInfo.key}.primary_platform`,
      label: 'Primary Platform',
      name: 'platform',
      component: 'dropdown',
      type: '',
      style: '',
      required: true,
      default: platformOptions[0].value,
      placeholder: '',
      colSpan: null,
      options: platformOptions,
      validations: [],
      config: {},
      group: {},
    },
    {
      uid: `${CreateDealSections.BasicInfo.key}.deal_value`,
      label: 'Deal Value',
      name: 'value',
      component: 'textInput',
      type: 'number',
      style: '',
      required: true,
      default: '',
      placeholder: '50,000',
      colSpan: null,
      options: [],
      validations: [],
      config: {},
      group: {},
    },
    {
      uid: `${CreateDealSections.BasicInfo.key}.brand_website`,
      label: 'Brand Website',
      name: 'brandWebsite',
      component: 'textInput',
      type: 'url',
      style: '',
      required: true,
      default: '',
      placeholder: 'https://www.nikeindia.in',
      colSpan: null,
      options: [],
      validations: [],
      config: {},
      group: {},
    },
    {
      uid: `${CreateDealSections.BasicInfo.key}.brand_industry`,
      label: 'Brand Industry',
      name: 'brandIndustry',
      component: 'dropdown',
      type: '',
      style: '',
      required: false,
      default: industryOptions[0].value,
      placeholder: '',
      colSpan: null,
      options: industryOptions,
      validations: [],
      config: {},
      group: {},
    },
    {
      uid: `${CreateDealSections.BasicInfo.key}.company_size`,
      label: 'Company Size',
      name: 'brandCompanySize',
      component: 'dropdown',
      type: '',
      style: '',
      required: false,
      default: companySizeOptions[0].value,
      placeholder: '',
      colSpan: null,
      options: companySizeOptions,
      validations: [],
      config: {},
      group: {},
    },
    {
      uid: `${CreateDealSections.BasicInfo.key}.deal_source`,
      label: 'Deal Source',
      name: 'source',
      component: 'dropdown',
      type: '',
      style: '',
      required: false,
      default: sourceOptions[0].value,
      placeholder: '',
      colSpan: null,
      options: sourceOptions,
      validations: [],
      config: {},
      group: {},
    },
    {
      uid: `${CreateDealSections.BasicInfo.key}.currency`,
      label: 'Currency',
      name: 'currency',
      component: 'dropdown',
      type: '',
      style: '',
      required: false,
      default: currencyOptions[0].value,
      placeholder: '',
      colSpan: null,
      options: currencyOptions,
      validations: [],
      config: {},
      group: {},
    },
  ],
}

CreateDealForm[CreateDealSections.ContactInfo.key] = {
  uid: `${CreateDealSections.ContactInfo.key}_section_2`,
  title: CreateDealSections.ContactInfo.label,
  fields: [
    {
      uid: `${CreateDealSections.ContactInfo.key}.contact_name`,
      label: 'Contact Name',
      name: 'contactName',
      component: 'textInput',
      type: 'text',
      style: '',
      required: true,
      default: '',
      placeholder: 'John Doe',
      colSpan: null,
      dropdown: [],
      validations: [],
      config: {},
      group: {},
    },
    {
      uid: `${CreateDealSections.ContactInfo.key}.contact_email`,
      label: 'Contact Email',
      name: 'contactEmail',
      component: 'textInput',
      type: 'email',
      style: '',
      required: true,
      default: '',
      placeholder: 'john@gmail.com',
      colSpan: null,
      dropdown: [],
      validations: [],
      config: {},
      group: {},
    },
    {
      uid: `${CreateDealSections.ContactInfo.key}.contact_phone`,
      label: 'Contact Phone (+91)',
      name: 'contactPhone',
      component: 'textInput',
      type: 'number',
      style: '',
      required: true,
      default: '',
      placeholder: '9876543210',
      colSpan: null,
      dropdown: [],
      validations: [],
      config: {},
      group: {},
    },
    {
      uid: `${CreateDealSections.ContactInfo.key}.designation`,
      label: 'Designation',
      name: 'contactDesignation',
      component: 'textInput',
      type: 'text',
      style: '',
      required: true,
      default: '',
      placeholder: 'Marketing Manager',
      colSpan: null,
      options: [],
      validations: [],
      config: {},
      group: {},
    },
    {
      uid: `${CreateDealSections.ContactInfo.key}.brand_instragram_handle`,
      label: 'Brand Instagram',
      name: 'brandInstagram',
      component: 'textInput',
      type: 'text',
      style: '',
      required: false,
      default: '',
      placeholder: '@nikeofficial',
      colSpan: null,
      options: [],
      validations: [],
      config: {},
      group: {},
    },
    {
      uid: `${CreateDealSections.ContactInfo.key}.brand_category`,
      label: 'Brand Category',
      name: 'brandCategory',
      component: 'dropdown',
      type: '',
      style: '',
      required: false,
      default: brandCategories[0].value,
      placeholder: '',
      colSpan: null,
      options: brandCategories,
      validations: [],
      config: {},
      group: {},
    },
  ],
}

CreateDealForm[CreateDealSections.DeliverablesInfo.key] = {
  uid: `${CreateDealSections.DeliverablesInfo.key}_section_3`,
  title: CreateDealSections.DeliverablesInfo.label,
  fields: [
    {
      uid: `${CreateDealSections.DeliverablesInfo.key}.deliverables`,
      label: 'Deliverables',
      name: 'deliverables',
      component: 'group',
      type: '',
      style: 'bg-form-group',
      required: false,
      default: '',
      placeholder: '',
      colSpan: 12,
      options: [],
      validations: [],
      config: {
        group: {
          canAddFields: true,
        },
      },
      group: [
        {
          uid: `${CreateDealSections.DeliverablesInfo.key}.deliverables.subField_1`,
          label: 'Platform',
          name: 'type',
          component: 'dropdown',
          type: '',
          style: '',
          required: true,
          default: contentOptions[0].value,
          placeholder: '',
          colSpan: 4,
          options: contentOptions,
          validations: [],
          config: {},
        },
        {
          uid: `${CreateDealSections.DeliverablesInfo.key}.deliverables.subField_2`,
          label: 'Quantity',
          name: 'quantity',
          component: 'textInput',
          type: 'number',
          style: '',
          required: true,
          default: '',
          placeholder: 'Number of posts',
          colSpan: 4,
          options: [],
          validations: [],
          config: {},
        },
        {
          uid: `${CreateDealSections.DeliverablesInfo.key}.deliverables.subField_3`,
          label: 'Description',
          name: 'description',
          component: 'textInput',
          type: 'text',
          style: '',
          required: false,
          default: '',
          placeholder: 'Add your description here',
          colSpan: 4,
          options: [],
          validations: [],
          config: {},
        },
      ],
    },
    {
      uid: `${CreateDealSections.DeliverablesInfo.key}.final_deadline`,
      label: 'Final Deadline',
      name: 'deadline',
      component: 'textInput',
      type: 'date',
      style: '',
      required: true,
      default: '',
      placeholder: '',
      colSpan: null,
      options: [],
      validations: [],
      config: {},
      group: {},
    },
    {
      uid: `${CreateDealSections.DeliverablesInfo.key}.priority_level`,
      label: 'Priority Level',
      name: 'priority',
      component: 'dropdown',
      type: '',
      style: '',
      required: true,
      default: { label: 'Low', value: 'low' },
      placeholder: '',
      colSpan: null,
      default: 'low',
      options: [
        { label: 'Low', value: 'low' },
        { label: 'Medium', value: 'medium' },
        { label: 'High', value: 'high' },
        { label: 'Urgent', value: 'urgent' },
      ],
      validations: [],
      config: {},
      group: {},
    },
    {
      uid: `${CreateDealSections.DeliverablesInfo.key}.campaign_start_date`,
      label: 'Campaign Start Date',
      name: 'campaignStartDate',
      component: 'textInput',
      type: 'date',
      style: '',
      required: false,
      default: '',
      placeholder: '',
      colSpan: null,
      options: [],
      validations: [],
      config: {},
      group: {},
    },
    {
      uid: `${CreateDealSections.DeliverablesInfo.key}.campaign_end_date`,
      label: 'Campaign End Date',
      name: 'campaignEndDate',
      component: 'textInput',
      type: 'date',
      style: '',
      required: false,
      default: '',
      placeholder: '',
      colSpan: null,
      options: [],
      validations: [],
      config: {},
      group: {},
    },
    {
      uid: `${CreateDealSections.DeliverablesInfo.key}.campaign_brief`,
      label: 'Campaign Brief',
      name: 'brief',
      component: 'textArea',
      type: '',
      style: '',
      required: false,
      default: '',
      placeholder: 'Describe the campaign requirements, goals, and guidelines...',
      colSpan: 12,
      options: [],
      validations: [],
      config: {},
      group: {},
    },
    {
      uid: `${CreateDealSections.DeliverablesInfo.key}.performance_targets`,
      label: 'Performance Targets (Optional)',
      name: 'performance',
      component: 'group',
      type: '',
      style: 'bg-form-group',
      required: false,
      default: '',
      placeholder: '',
      colSpan: 12,
      options: [],
      validations: [],
      config: {
        group: {
          canAddFields: false, // Boolean Value for Button & Showing added field count
        },
      },
      group: [
        {
          uid: `${CreateDealSections.DeliverablesInfo.key}.track_metrics.subField_1`,
          label: 'Track Performance Metrics',
          name: 'isTracked',
          component: 'textInput',
          type: 'checkbox',
          style: '',
          required: false,
          default: '',
          placeholder: '',
          colSpan: 12,
          options: [],
          validations: [],
          config: {},
          group: {},
        },
        {
          uid: `${CreateDealSections.DeliverablesInfo.key}.min_views.subField_2`,
          label: 'Minimum Views',
          name: 'views',
          component: 'textInput',
          type: 'number',
          style: '',
          required: false,
          default: '',
          placeholder: '10000',
          colSpan: null,
          options: [],
          validations: [],
          config: {
            showIf: { field: 'performance.isTracked', operation: 'equals', to: 'true' },
          },
          group: {},
        },
        {
          uid: `${CreateDealSections.DeliverablesInfo.key}.min_likes.subField_3`,
          label: 'Minimum Likes',
          name: 'likes',
          component: 'textInput',
          type: 'number',
          style: '',
          required: false,
          default: '',
          placeholder: '700',
          colSpan: null,
          options: [],
          validations: [],
          config: {
            showIf: { field: 'performance.isTracked', operation: 'equals', to: 'true' },
          },
          group: {},
        },
        {
          uid: `${CreateDealSections.DeliverablesInfo.key}.min_comments.subField_4`,
          label: 'Minimum Comments',
          name: 'comments',
          component: 'textInput',
          type: 'number',
          style: '',
          required: false,
          default: '',
          placeholder: '100',
          colSpan: null,
          options: [],
          validations: [],
          config: {
            showIf: { field: 'performance.isTracked', operation: 'equals', to: 'true' },
          },
          group: {},
        },
        {
          uid: `${CreateDealSections.DeliverablesInfo.key}.min_likes.subField_5`,
          label: 'Engadgement Rate(%)',
          name: 'engadgement',
          component: 'textInput',
          type: 'number',
          style: '',
          required: false,
          default: '',
          placeholder: '3.5',
          colSpan: null,
          options: [],
          validations: [],
          config: {
            showIf: { field: 'performance.isTracked', operation: 'equals', to: 'true' },
          },
          group: {},
        },
      ],
    },
  ],
}

CreateDealForm[CreateDealSections.PaymentInfo.key] = {
  uid: `${CreateDealSections.PaymentInfo.key}_section_4`,
  title: CreateDealSections.PaymentInfo.label,
  fields: [
    {
      uid: `${CreateDealSections.PaymentInfo.key}.payment_terms`,
      label: 'Payment Terms',
      name: 'paymentTerms',
      component: 'dropdown',
      type: '',
      style: '',
      required: true,
      default: paymentTermsOptions[0].value,
      placeholder: '',
      options: paymentTermsOptions,
      colSpan: null,
      validations: [],
      config: {},
      group: {},
    },
    {
      uid: `${CreateDealSections.PaymentInfo.key}.payment_method`,
      label: 'Payment Method',
      name: 'paymentMethod',
      component: 'dropdown',
      type: '',
      style: '',
      required: true,
      default: { label: 'Bank Transfer', value: 'bank_transfer' },
      placeholder: '',
      options: [
        { label: 'Bank Transfer', value: 'bank_transfer' },
        { label: 'UPI', value: 'upi' },
        { label: 'Cheque', value: 'cheque' },
        { label: 'Cash', value: 'cash' },
        { label: 'PayPal', value: 'paypal' },
        { label: 'Other', value: 'other' },
      ],
      colSpan: null,
      validations: [],
      config: {},
      group: {},
    },
    {
      uid: `${CreateDealSections.PaymentInfo.key}.gst_applicable`,
      label: 'GST Applicable (18%)',
      name: 'gstApplicable',
      component: 'textInput',
      type: 'checkbox',
      style: '',
      required: false,
      default: '',
      placeholder: '',
      options: [],
      colSpan: null,
      validations: [],
      config: {},
      group: {},
    },
    {
      uid: `${CreateDealSections.PaymentInfo.key}.tds_applicable`,
      label: 'TDS Applicable (10%) (For individual/HUF)',
      name: 'tdsApplicable',
      component: 'textInput',
      type: 'checkbox',
      style: '',
      required: false,
      default: '',
      placeholder: '',
      options: [],
      colSpan: null,
      validations: [],
      config: {},
      group: {},
    },
    {
      uid: `${CreateDealSections.PaymentInfo.key}.gst_number`,
      label: 'GST Number (Optional)',
      name: 'gstNumber',
      component: 'textInput',
      type: 'text',
      style: '',
      required: false,
      default: '',
      placeholder: '22AAAAAO00OAIZ5',
      options: [],
      colSpan: null,
      validations: [],
      config: {},
      group: {},
    },
  ],
}

CreateDealForm[CreateDealSections.AdditionalInfo.key] = {
  uid: `${CreateDealSections.AdditionalInfo.key}_section_5`,
  title: CreateDealSections.AdditionalInfo.label,
  fields: [
    {
      uid: `${CreateDealSections.AdditionalInfo.key}.tags`,
      label: 'Tags (Press Enter to add)',
      name: 'tags',
      component: 'tagsInput',
      type: '',
      style: '',
      required: false,
      default: '',
      placeholder: 'Add Tags...',
      colSpan: 12,
      options: [],
      validations: [],
      config: {},
      group: {},
    },
    {
      uid: `${CreateDealSections.AdditionalInfo.key}.payment_terms`,
      label: 'Internal Notes',
      name: 'internalNotes',
      component: 'textArea',
      type: 'text',
      style: '',
      required: false,
      default: '',
      placeholder: 'Any internal notes or reminders...',
      colSpan: 12,
      options: paymentTermsOptions,
      validations: [],
      config: {},
      group: {},
    },
    {
      uid: `${CreateDealSections.DeliverablesInfo.key}.content_guidelines`,
      label: 'Content Guidelines (Optional)',
      name: 'contentGuidelines',
      component: 'group',
      type: '',
      style: 'bg-form-group',
      required: false,
      default: '',
      placeholder: '',
      colSpan: 12,
      options: [],
      validations: [],
      config: {
        group: {
          canAddFields: false,
        },
      },
      group: [
        {
          uid: `${CreateDealSections.DeliverablesInfo.key}.tone.subField_1`,
          label: 'Content Tone',
          name: 'tone',
          component: 'dropdown',
          type: '',
          style: '',
          required: false,
          default: toneOptions[0].value,
          placeholder: '',
          colSpan: null,
          options: toneOptions,
          validations: [],
          config: {},
          group: {},
        },
        {
          uid: `${CreateDealSections.DeliverablesInfo.key}.style.subField_2`,
          label: 'Content Style',
          name: 'style',
          component: 'textInput',
          type: 'text',
          style: '',
          required: false,
          default: '',
          placeholder: 'Minimalist, Vibrant',
          colSpan: null,
          options: [],
          validations: [],
          config: {},
          group: {},
        },
      ],
    },
  ],
}

const FieldValidationRules = {
  contactEmail: (val) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(val),
  contactPhone: (val) => /^[6-9]\d{9}$/.test(val),
  brandWebsite: (val) => /^https?:\/\/.+\..+/.test(val),
}

export { CreateDealForm, FieldValidationRules }
