import {
  Briefcase,
  Building,
  Building2,
  Calendar,
  Coins,
  DollarSign,
  Globe,
  Share2,
  Users,
} from 'lucide-react'
import { DealsConstants } from '../../utils/constants'

const { Steps } = DealsConstants

const {
  platformOptions,
  sourceOptions,
  industryOptions,
  companySizeOptions,
  currencyOptions,
  brandCategories,
  paymentTermsOptions,
} = DealsConstants

const CreateDealFields = {}

CreateDealFields[Steps.BASIC_INFO] = {
  id: 'basic_information_1',
  title: 'Basic Information',
  fields: [
    {
      id: 'bi_field_1',
      isRequired: true,
      label: 'Brand Deal',
      icon: null,
      name: 'title',
      field: 'text',
      type: 'text',
      options: [],
      customStyle: 'grid-item-full',
      placeholder: 'Instagram Campaign - Nike',
      showId: {},
      defaultValue: '',
    },
    {
      id: 'bi_field_2',
      isRequired: true,
      label: 'Brand Name',
      icon: Building,
      name: 'brandName',
      field: 'text',
      type: 'text',
      options: [],
      customStyle: '',
      placeholder: 'Nike India',
      showId: {},
      defaultValue: '',
    },
    {
      id: 'bi_field_3',
      isRequired: false,
      label: 'Brand Website',
      icon: Globe,
      name: 'brandWebsite',
      field: 'text',
      type: 'url',
      options: [],
      customStyle: '',
      placeholder: 'https://www.example.com',
      showId: {},
      defaultValue: '',
    },
    {
      id: 'bi_field_4',
      isRequired: false,
      label: 'Brand Industry',
      icon: Building2,
      name: 'brandIndustry',
      field: 'dropdown',
      type: '',
      options: industryOptions,
      customStyle: '',
      placeholder: '',
      showId: {},
      defaultValue: industryOptions[0].value,
    },
    {
      id: 'bi_field_5',
      isRequired: false,
      label: 'Company Size',
      icon: Users,
      name: 'brandCompanySize',
      field: 'dropdown',
      type: '',
      options: companySizeOptions,
      customStyle: '',
      placeholder: '',
      showId: {},
      defaultValue: companySizeOptions[0].value,
    },
    {
      id: 'bi_field_6',
      isRequired: true,
      label: 'Primary Platform',
      icon: Share2,
      name: 'platform',
      field: 'dropdown',
      type: '',
      options: platformOptions,
      customStyle: '',
      placeholder: '',
      showId: {},
      defaultValue: platformOptions[0].value,
    },
    {
      id: 'bi_field_7',
      isRequired: false,
      label: 'Deal Source',
      icon: Briefcase,
      name: 'source',
      field: 'dropdown',
      type: '',
      options: sourceOptions,
      customStyle: '',
      placeholder: '',
      showId: {},
      defaultValue: sourceOptions[0].value,
    },
    {
      id: 'bi_subField_1',
      isRequired: true,
      label: 'Referral Source',
      icon: Briefcase,
      name: 'referralSource',
      field: 'text',
      type: 'text',
      options: [],
      customStyle: '',
      placeholder: 'Who Referred this deal?',
      showIf: { field: 'source', value: 'referral', operation: 'equals' },
      defaultValue: '',
    },
    {
      id: 'bi_field_8',
      isRequired: true,
      label: 'Deal value',
      icon: Coins,
      name: 'value',
      field: 'text',
      type: 'number',
      options: [],
      customStyle: '',
      placeholder: '50,000',
      showId: {},
      defaultValue: '',
    },
    {
      id: 'bi_field_9',
      isRequired: true,
      label: 'Currency',
      icon: DollarSign,
      name: 'currency',
      field: 'dropdown',
      type: '',
      options: currencyOptions,
      customStyle: '',
      placeholder: '',
      showId: {},
      defaultValue: currencyOptions[0].value,
    },
  ],
}

CreateDealFields[Steps.CONTACT] = {
  id: 'contact_2',
  title: 'Contact Details',
  fields: [
    {
      id: 'c_field_1',
      isRequired: true,
      label: 'Contact Name',
      icon: null,
      name: 'contactName',
      field: 'text',
      type: 'text',
      options: [],
      customStyle: '',
      placeholder: 'John Doe',
      defaultValue: '',
    },
    {
      id: 'c_field_2',
      isRequired: true,
      label: 'Contact Email',
      icon: Building,
      name: 'contactEmail',
      field: 'text',
      type: 'email',
      options: [],
      customStyle: '',
      placeholder: 'john@gmail.com',
      defaultValue: '',
    },
    {
      id: 'c_field_3',
      isRequired: true,
      label: 'Contact Phone',
      icon: Globe,
      name: 'contactPhone',
      field: 'text',
      type: 'tel',
      options: [],
      customStyle: '',
      placeholder: '+91 9823 726423',
      defaultValue: '',
    },
    {
      id: 'c_field_4',
      isRequired: false,
      label: 'Designation',
      icon: Building2,
      name: 'contactDesignation',
      field: 'text',
      type: 'text',
      options: industryOptions,
      customStyle: '',
      placeholder: 'Marketing Manager',
      defaultValue: '',
    },
    {
      id: 'c_field_5',
      isRequired: false,
      label: 'Brand Instagram',
      icon: Users,
      name: 'brandInstagram',
      field: 'text',
      type: 'text',
      options: [],
      customStyle: '',
      placeholder: '@nikeofficial',
      defaultValue: '',
    },
    {
      id: 'c_field_6',
      isRequired: true,
      label: 'Brand Category',
      icon: Share2,
      name: 'brandCategory',
      field: 'dropdown',
      type: '',
      options: brandCategories,
      customStyle: '',
      placeholder: '',
      defaultValue: brandCategories[0].value,
    },
  ],
}
CreateDealFields[Steps.DELIVERABLES] = {
  id: 'deliverables_3',
  title: 'Deliverables & Timeline',
  fields: [
    {
      id: 'd_field_1',
      isRequired: true,
      label: 'Final Deadline',
      icon: Calendar,
      name: 'deadline',
      field: 'text',
      type: 'date',
      options: [],
      customStyle: '',
      placeholder: '',
    },
    {
      id: 'd_field_2',
      isRequired: true,
      label: 'Priority Level',
      icon: null,
      name: 'priority',
      field: 'dropdown',
      type: '',
      options: [
        { label: 'Low', value: 'low' },
        { label: 'Medium', value: 'medium' },
        { label: 'High', value: 'high' },
        { label: 'Urgent', value: 'urgent' },
      ],
      customStyle: '',
      placeholder: '',
    },
    {
      id: 'd_field_3',
      isRequired: false,
      label: 'Campaign Start Date',
      icon: Calendar,
      name: 'campaignStartDate',
      field: 'text',
      type: 'date',
      options: [],
      customStyle: '',
      placeholder: '',
    },
    {
      id: 'd_field_4',
      isRequired: false,
      label: 'Campaign End Date',
      icon: Calendar,
      name: 'campaignEndDate',
      field: 'text',
      type: 'date',
      options: [],
      customStyle: '',
      placeholder: '',
    },
    {
      id: 'd_field_5',
      isRequired: false,
      label: 'Campaign Brief',
      icon: null,
      name: 'brief',
      field: 'textarea',
      type: '',
      options: [],
      customStyle: 'grid-item-full',
      placeholder: 'Describe the campaign requirements, goals, and guidelines...',
    },
  ],
}
CreateDealFields[Steps.PAYMENT] = {
  id: 'payment_4',
  title: 'Payment & Terms',
  fields: [
    {
      id: 'p_field_1',
      isRequired: true,
      label: 'Payment Terms',
      icon: null,
      name: 'paymentTerms',
      field: 'dropdown',
      type: '',
      options: paymentTermsOptions,
      customStyle: '',
      placeholder: '',
    },
    {
      id: 'p_field_2',
      isRequired: true,
      label: 'Payment Method',
      icon: null,
      name: 'paymentMethod',
      field: 'dropdown',
      type: '',
      options: [
        { label: 'Bank Transfer', value: 'bank_transfer' },
        { label: 'UPI', value: 'upi' },
        { label: 'Cheque', value: 'cheque' },
        { label: 'Cash', value: 'cash' },
        { label: 'PayPal', value: 'paypal' },
        { label: 'Other', value: 'other' },
      ],
      customStyle: '',
      placeholder: '',
    },
    {
      id: 'p_field_3',
      isRequired: false,
      label: 'GST Applicable (18%)',
      icon: null,
      name: 'gstApplicable',
      field: 'text',
      type: 'checkbox',
      options: [],
      customStyle: 'checkbox',
      placeholder: '',
    },
    {
      id: 'p_field_4',
      isRequired: false,
      label: 'TDS Applicable (10%)(For individuals/HUF)',
      icon: null,
      name: 'tdsApplicable',
      field: 'text',
      type: 'checkbox',
      options: [],
      customStyle: {
        display: 'flex',
        alignItems: 'center',
        gap: '0.5rem',
      },
      placeholder: '',
    },
    {
      id: 'p_field_5',
      isRequired: false,
      label: 'GST Number (Optional)',
      icon: null,
      name: 'gstNumber',
      field: 'text',
      type: 'text',
      options: [],
      customStyle: '',
      placeholder: '22AAAAA0000A1Z5',
    },
  ],
}
CreateDealFields[Steps.ADDITIONAL] = {
  id: 'additional_5',
  title: 'Additional Details',
  fields: [
    {
      id: 'd_field_1',
      isRequired: true,
      label: 'Internal Notes',
      icon: null,
      name: 'internalNotes',
      field: 'textarea',
      type: '',
      options: paymentTermsOptions,
      customStyle: 'grid-item-full',
      placeholder: 'Any internal notes or reminders...',
    },
  ],
}

function generateInitialState() {
  let initialState = {}

  for (const stepKey in CreateDealFields) {
    CreateDealFields[stepKey].fields.forEach((field) => {
      initialState[field.name] = {
        value: field.defaultValue ?? '',
        error: '',
      }
    })
  }

  return initialState
}

export { CreateDealFields, generateInitialState }
